name = "StreamStats"
uuid = "3001c9e7-7664-45b9-94a8-10486f7ca6c4"
authors = ["z4rd0s <mail@cboll.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
